### ISSUE TITLE
derelict-ft not found in windows

### ISSUE THREAD

**Issue by zhaopuming** [buggins/dlangui#292]
In windows 10, when running example of dlangui, dub outputs:

```
Non-optional dependency derelict-ft of dlangui not found in dependency tree!?.
```

I didn't have this problem in earlier versions of dlangui.
How can I install this dependency? dub upgrade does not work

**Comment by buggins** [comment]
isn't it fixed in latest release?

**Comment by Vild** [comment]
I'm having this problem on archlinux.
I've tried to remove the .dub directory, but this doesn't fix the issue.

This is what I get when I run `dub run :helloworld --vverbose` http://ix.io/1ndp
Running just `dub` to build dlangui works without any problems. http://ix.io/1ndr

Could this be a dub bug?

DUB version 1.0.0
DMD64 D Compiler v2.071.1

**Comment by buggins** [comment]
did you try `cd examples/helloworld; dub run` ? Does it work?
Did you try `dub upgrade --force-remove` ?
I've just tried under windows, inside cloned dlangui repository directory `dub run :helloworld` - works for me. DUB version 1.0.0, built on Jun 20 2016
As well, tried under ubunu linux - inside cloned dlangui, `dub upgrade --force-remove; dub run :helloworld` - works ok. dub version is 0.9.24

**Comment by buggins** [comment]
dmd 2.070.2 on linux, 2.071.1 on windows

**Comment by Vild** [comment]
Running `dub run` in examples/helloworld worked! and after that `dub run :helloworld` worked too.
I have to cd into each example directory and run `dub` to use the `dub run :NAME` command in the root folder.

This must be some sort of dub bug.

**Comment by buggins** [comment]
I believe I can close this issue
